import mongoose from 'mongoose'
const BikeSchema = new mongoose.Schema({


make: {type: String, default:''},
model: {type: String, default:''},
type: {type:String, default:'Road Bike'},
frameSize: {type: String, default:''},
frameReach: {type: Number, default:0},
frameStack: {type: Number, default:0},
effectiveTopTube: {type: Number, default:0},
seatPostOffset: {type: Number, default:0},
saddleMake: {type: String, default:''},
saddleModel: {type: String, default:''},
saddleWidth: {type: Number, default:0},
crankLength: {type: Number, default:0},
pedalType: {type: String, default:'Road'},
pedalMakeModel: {type: String, default:''},
stemLength: {type: Number, default:0},
stemType:{type: String, default:'Standard'},
stemAngle: {type: Number, default:0},
spacersBelow: {type: Number, default:0},
spacersAbove: {type: Number, default:0},
handlebarWidth: {type: Number, default:0},
handlebarReach: {type: Number, default:0},
shifterType: {type: String, default:'Mechanical'},
brakeType: {type: String, default:'Rim'},
saddleHeight: {type: Number, default:0},
saddleHeightBB: {type: Number, default:0},
saddleSetBack: {type: Number, default:0},
saddleAngle: {type: Number, default:0},
saddleNoseToBar: {type: Number, default:0},
saddleNoseToHood: {type: Number, default:0},
saddleToBarDrop: {type: Number, default:0},
handlebarReachHX: {type: Number, default:0}, 
handlebarStackHY: {type: Number, default:0},
handlebarAngle: {type: Number, default:0},
hoodAngle: {type: Number, default:0},
cleatModel: {type: String, default:''},
shoeBrand: {type: String, default:''},
shoeModel:  {type: String, default:''},
shoeSize: {type: Number, default:0},
insoles: {type: String, default:''},
cleatAdjustments: {type: String, default:''},
cleatModifications: {type: String, default:''},
bikeLength: {type: Number, default:0},
mtbWheelSize:{type: String ,default:''},
mtbSeatPostType: {type: String, default:'Rigid'},
mtbSaddleNoseToGripEnd: {type: Number, default:0},
mtbSaddleToGripCenterDropRise: {type: Number, default:0},
ttBasebarWidth: {type: Number, default:0},
ttAerobarType: {type: String, default:'Integrated'},
ttAerobarMakeModel: {type: String, default:''},
ttExtensionsShape: {type: String, default:''},
ttRisers: {type: String, default:''},
ttPadsMakeModel: {type: String, default:''},
ttSaddleToPadCenterDrop: {type: Number, default:0},
ttSaddleNoseToPadRear:{type: Number, default:0},
ttSaddleNoseToEndOfExtensions:{type: Number, default:0},
ttExtensionWidthAtClamps:{type: Number, default:0},
ttExtensionWidthAtEnd:{type: Number, default:0},
ttExtensionAngle:{type: Number, default:0},
ttPadWidth:{type: Number, default:0},
ttPadXReachRearOfPad: {type: Number, default:0},
ttPadXReachCenterOfPad: {type: Number, default:0},
ttPadYStackRearOfPad: {type: Number, default:0},
ttBasebarReachX: {type: Number, default:0},
ttBasebarStackY: {type: Number, default:0},
ttBasebarAngle: {type: Number, default:0},
notes:{type: String, default: ''},
confidentialNotes:{type:String,default:''},
ownedBy: {type: mongoose.Schema.ObjectId, ref: 'Cyclist'},
createdBy: {type: mongoose.Schema.ObjectId, ref: 'User'},
updated: {type: Date, default: Date.now},
created: {type: Date, default: Date.now},
fitHistory: [{}]

})


export default mongoose.model('Bike', BikeSchema)
